/**
 * Export Analytics data to PDF
 * Uses jsPDF to generate a formatted PDF report
 */

import jsPDF from 'jspdf';

interface QuestionStats {
  questionId: string;
  questionLabel: string;
  totalResponses: number;
  options: {
    value: string;
    label: string;
    count: number;
    percentage: number;
  }[];
  textResponses?: string[];
}

/**
 * Export analytics statistics to PDF
 */
export function exportAnalyticsToPDF(
  stats: QuestionStats[],
  totalResponses: number
) {
  const doc = new jsPDF();
  
  // Page settings
  const pageWidth = doc.internal.pageSize.getWidth();
  const pageHeight = doc.internal.pageSize.getHeight();
  const margin = 20;
  const contentWidth = pageWidth - (margin * 2);
  let yPosition = margin;

  // Helper function to add new page if needed
  const checkPageBreak = (requiredSpace: number) => {
    if (yPosition + requiredSpace > pageHeight - margin) {
      doc.addPage();
      yPosition = margin;
      return true;
    }
    return false;
  };

  // Title
  doc.setFontSize(24);
  doc.setFont('helvetica', 'bold');
  doc.text('Analytics Report', margin, yPosition);
  yPosition += 10;

  // Subtitle
  doc.setFontSize(12);
  doc.setFont('helvetica', 'normal');
  doc.setTextColor(100, 100, 100);
  doc.text(`Total Responses: ${totalResponses}`, margin, yPosition);
  yPosition += 5;
  
  const currentDate = new Date().toLocaleDateString('en-US', {
    year: 'numeric',
    month: 'long',
    day: 'numeric',
  });
  doc.text(`Generated: ${currentDate}`, margin, yPosition);
  yPosition += 15;

  // Reset text color
  doc.setTextColor(0, 0, 0);

  // Process each question
  stats.forEach((stat, index) => {
    // Check if we need a new page for this question
    checkPageBreak(60);

    // Question title
    doc.setFontSize(14);
    doc.setFont('helvetica', 'bold');
    const questionLines = doc.splitTextToSize(stat.questionLabel, contentWidth);
    questionLines.forEach((line: string) => {
      doc.text(line, margin, yPosition);
      yPosition += 7;
    });

    // Response count
    doc.setFontSize(10);
    doc.setFont('helvetica', 'normal');
    doc.setTextColor(100, 100, 100);
    doc.text(`${stat.totalResponses} responses`, margin, yPosition);
    yPosition += 8;
    doc.setTextColor(0, 0, 0);

    // Options
    stat.options.forEach((option) => {
      checkPageBreak(15);

      // Option label
      doc.setFontSize(10);
      doc.setFont('helvetica', 'normal');
      const optionText = `${option.label}`;
      doc.text(optionText, margin + 5, yPosition);

      // Count and percentage
      const statsText = `${option.count} (${option.percentage.toFixed(1)}%)`;
      const statsWidth = doc.getTextWidth(statsText);
      doc.text(statsText, pageWidth - margin - statsWidth, yPosition);

      yPosition += 5;

      // Progress bar
      const barWidth = contentWidth - 10;
      const barHeight = 4;
      const barX = margin + 5;
      
      // Background bar (gray)
      doc.setFillColor(230, 230, 230);
      doc.rect(barX, yPosition, barWidth, barHeight, 'F');
      
      // Filled bar (black)
      const fillWidth = (barWidth * option.percentage) / 100;
      doc.setFillColor(0, 0, 0);
      doc.rect(barX, yPosition, fillWidth, barHeight, 'F');

      yPosition += 10;
    });

    // Text responses if any
    if (stat.textResponses && stat.textResponses.length > 0) {
      checkPageBreak(20);
      
      doc.setFontSize(10);
      doc.setFont('helvetica', 'italic');
      doc.setTextColor(100, 100, 100);
      doc.text(`Text responses (${stat.textResponses.length}):`, margin + 5, yPosition);
      yPosition += 6;

      stat.textResponses.forEach((text) => {
        checkPageBreak(10);
        
        doc.setFontSize(9);
        doc.setFont('helvetica', 'normal');
        const textLines = doc.splitTextToSize(`"${text}"`, contentWidth - 10);
        textLines.forEach((line: string) => {
          doc.text(line, margin + 10, yPosition);
          yPosition += 5;
        });
      });
      
      doc.setTextColor(0, 0, 0);
      yPosition += 5;
    }

    // Separator line between questions
    if (index < stats.length - 1) {
      checkPageBreak(10);
      doc.setDrawColor(200, 200, 200);
      doc.line(margin, yPosition, pageWidth - margin, yPosition);
      yPosition += 15;
    }
  });

  // Footer on last page
  doc.setFontSize(8);
  doc.setTextColor(150, 150, 150);
  doc.text(
    'Generated by Regalo Analytics Dashboard',
    pageWidth / 2,
    pageHeight - 10,
    { align: 'center' }
  );

  // Save the PDF
  const fileName = `analytics-report-${new Date().toISOString().split('T')[0]}.pdf`;
  doc.save(fileName);
}
